@server= http://localhost:3000/v1

###
GET {{server}}

### sign up
post {{server}}/auth/signup
Content-Type: application/json

{
    "firstName": "Amy",
    "lastName": "James",
    "email": "amyJames@gmail.com",
    "password": "army89$",
    "phoneNo": "+2347064325528",
    "txPin": "1077"
  }
